import type { CSSProperties } from "react"

export const guideStyles: Record<string, React.CSSProperties> = {
    overlay: {
        position: 'fixed',
        inset:    0,
        zIndex:   9998,
    },
    highlight: {
        position:      'fixed',
        borderRadius:  '8px',
        border:        '2px solid #f59e0b',
        boxShadow:     '0 0 16px rgba(245,158,11,0.4)',
        pointerEvents: 'none',
        zIndex:        9999,
    },
    tooltip: {
        position:     'fixed',
        zIndex:       10000,
        background:   '#12192b',
        border:       '1px solid rgba(245,158,11,0.3)',
        borderRadius: '12px',
        padding:      '24px',
        width:        '320px',
        boxShadow:    '0 8px 32px rgba(0,0,0,0.6)',
        fontFamily:   'inherit',
    },
    header: {
        display:        'flex',
        justifyContent: 'space-between',
        alignItems:     'flex-start',
        marginBottom:   '12px',
    },
    label: {
        fontSize:      '11px',
        color:         '#f59e0b',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
        marginBottom:  '4px',
    },
    title: {
        fontSize:   '18px',
        fontWeight: 700,
        color:      '#ffffff',
    },
    closeBtn: {
        background: 'none',
        border:     'none',
        color:      '#6b7280',
        cursor:     'pointer',
        fontSize:   '20px',
        lineHeight: '1',
        padding:    '0 0 0 8px',
    },
    description: {
        fontSize:   '14px',
        color:      '#9ca3af',
        lineHeight: '1.6',
        margin:     '0 0 20px 0',
    },
    dotsRow: {
        display:      'flex',
        gap:          '6px',
        marginBottom: '20px',
    },
    dotActive: {
        width:        '20px',
        height:       '6px',
        borderRadius: '3px',
        background:   '#f59e0b',
        transition:   'all 0.2s ease',
    },
    dotInactive: {
        width:        '6px',
        height:       '6px',
        borderRadius: '3px',
        background:   '#374151',
        transition:   'all 0.2s ease',
    },
    buttonsRow: {
        display: 'flex',
        gap:     '8px',
    },
    btnPrev: {
        flex:          1,
        padding:       '10px',
        background:    'transparent',
        border:        '1px solid #374151',
        borderRadius:  '8px',
        color:         '#9ca3af',
        cursor:        'pointer',
        fontSize:      '13px',
        letterSpacing: '0.05em',
    },
    btnNext: {
        flex:          1,
        padding:       '10px',
        background:    '#f59e0b',
        border:        'none',
        borderRadius:  '8px',
        color:         '#000',
        cursor:        'pointer',
        fontSize:      '13px',
        fontWeight:    700,
        letterSpacing: '0.05em',
    },
    skipRow: {
        textAlign: 'center',
        marginTop: '12px',
    },
    skipBtn: {
        background:    'none',
        border:        'none',
        color:         '#4b5563',
        cursor:        'pointer',
        fontSize:      '12px',
        letterSpacing: '0.05em',
    },
}

export const boutonStyles: CSSProperties ={
    position: 'fixed',
    bottom: '24px',
    right: '24px',
    zIndex: 9000,
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    background: '#12192b',
    border: '1px solid rgba(245,158,11,0.4)',
    color: '#f59e0b',
    fontSize: '18px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    transition: 'all 0.2s ease'
}
