import { EnemyTag } from "@fight/fight.types";

export const SMALL_RANGE_MAP_COMPOSITIONS: Record<number, EnemyTag[]> = {
    1: ["ENEMY_MELEE"],
    2: ["ENEMY_MELEE", "ENEMY_MELEE"],
    3: ["ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
    4: ["ENEMY_TANK",  "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
    5: ["ENEMY_TANK",  "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
    6: ["ENEMY_TANK",  "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
    7: ["ENEMY_TANK",  "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
    8: ["ENEMY_TANK",  "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE"],
}

export const MID_RANGE_MAP_COMPOSITIONS: Record<number, EnemyTag[]> = {
    1: ["ENEMY_RANGED"],
    2: ["ENEMY_RANGED", "ENEMY_MELEE"],
    3: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE"],
    4: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE"],
    5: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_TANK"],
    6: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_TANK"],
    7: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_TANK"],
    8: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_MELEE", "ENEMY_TANK", "ENEMY_BOSS"],
}

export const LONG_RANGE_MAP_COMPOSITIONS: Record<number, EnemyTag[]> = {
    1: ["ENEMY_RANGED"],
    2: ["ENEMY_RANGED", "ENEMY_RANGED"],
    3: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED"],
    4: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED"],
    5: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_TANK"],
    6: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_TANK", "ENEMY_MELEE"],
    7: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_TANK", "ENEMY_MELEE"],
    8: ["ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_RANGED", "ENEMY_TANK", "ENEMY_MELEE", "ENEMY_BOSS"],
}