export default {
    container: "w-screen h-screen relative overflow-hidden flex flex-col text-slate-200 bg-black selection:bg-amber-500/30",
    bgContainer: "absolute inset-0 z-0 overflow-hidden",
    bgImage: "w-full h-full object-cover opacity-100 blur-[1px] animate-[ambient-zoom_10s_ease-in-out_infinite_alternate]",
    overlay: "absolute inset-0 bg-gradient-to-b from-slate-950/95 via-slate-950/70 to-slate-950/95 z-0 pointer-events-none",
    scanlines: "absolute inset-0 pointer-events-none z-0 opacity-20 bg-[linear-gradient(rgba(255,255,255,0)_50%,rgba(0,0,0,0.25)_50%)] bg-[length:100%_4px]",
    foreground: "relative z-10 flex flex-col h-full",
    titleContainer: "flex-none pt-8 pb-4 text-center",
    mainTitle: "text-4xl font-black tracking-widest text-transparent bg-clip-text bg-gradient-to-b from-white to-slate-400 uppercase drop-shadow-[0_0_20px_rgba(255,255,255,0.1)]",
    subTitle: "text-amber-500/80 text-xs font-bold tracking-[0.5em] uppercase mt-3 animate-pulse",
    grid: "flex-1 flex items-center justify-center gap-16 min-h-0 py-8",
    cardWrapper1: "h-full animate-[float_4s_ease-in-out_infinite]",
    cardWrapper2: "h-full animate-[float_4s_ease-in-out_infinite_0.1s]",
    footer: "flex-none flex justify-center pb-12 pt-4 relative z-20",
    launchButton: "px-16 py-4 bg-slate-900 border-2 border-slate-800 rounded-xl text-slate-600 font-black tracking-widest text-sm cursor-not-allowed uppercase shadow-2xl relative overflow-hidden group",
}